name: heroku-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create env file
      run: |
        touch .env
        {
          echo PORT=5000
          echo TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
          echo DB_URL=${{ secrets.DB_URL }}
        } > .env
        cat .env

    - uses: akhileshns/heroku-deploy@v3.11.10
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        env_file: ".env"
