name: Start-creating-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Create env file
      run: |
        touch .env
        echo TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} >> .env
        echo DB_URL=${{ secrets.DB_URL }} >> .env
        cat .env